### ISSUE TITLE
Add Lindy column

### ISSUE THREAD

**Issue by Valdorff** [StakingDirectory/StakingDirectory#39]
https://ethereum.org/en/staking/pools/ use "Battle tested" as a category meaning that the protocol has been live for a year. [Lindy](https://en.wikipedia.org/wiki/Lindy_effect) is a well-known security component, as much as audits and bounties, so I think it should be represented at the top level in some way. My suggestion would be red x under 3 months, yellow ~ 3-12 months, and green check from 12 months on. But I'll note I'm definitely biased (RP guy here), so I shouldn't be making that call.

I acknowledge that this info shows up a little in the expanded view where it shows launch date, but that also doesn't use any color to differentiate levels of Lindy. Again - I think this is a critical metric in web3.

**Comment by EridianAlpha** [comment]
Thanks for the suggestion 🙂 This was in the initial design, but it was removed as "Battle tested" is a subjective metric and people will always argue over what it means to be battle tested. Rather than grouping "Battle tested" into discrete categories, there could be a column showing "Age" that allows users to make up their own minds about what they view to be an acceptable level of Lindy risk.

I do agree that it's useful for people to know that a project has been live for 1 month vs 2 years, which is why the mainnet launch date is collected and shown.

I'll work on the designs of how this could be displayed directly on the table.

**Comment by EridianAlpha** [comment]
Hey @Valdorff, this column is being added as "Mainnet Launch" in the next deployment. You can see the example site here: https://staking-directory-git-blue-links-stakingdirectory.vercel.app
